-- ==============================================================================
-- SISTEMA INTEGRAL DE GESTIÓN DE SOPORTE TECNOLÓGICO UNIVERSITARIO (API II)
-- Script de Creación de Base de Datos para Supabase (PostgreSQL)
-- ==============================================================================

-- 1. EXTENSIONES
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. TABLAS BASE Y CATÁLOGOS

-- Catálogo de Roles
CREATE TABLE IF NOT EXISTS ROLES (
    id_rol INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL UNIQUE
);

-- Catálogo de Aulas / Laboratorios
CREATE TABLE IF NOT EXISTS AULAS (
    id_aula INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    ubicacion VARCHAR(100) NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

-- Catálogo de Tipos de Problema
CREATE TABLE IF NOT EXISTS TIPOS_PROBLEMA (
    id_tipo_problema INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE
);

-- 3. PERFILES DE USUARIOS (Vinculados a Supabase Auth)
-- id_usuario es UUID y actúa como FK a auth.users(id).
-- La autenticación y hashing de contraseñas es gestionada por Supabase Auth.
CREATE TABLE IF NOT EXISTS USUARIOS (
    id_usuario UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    nombre VARCHAR(50) NOT NULL,
    apellido VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    telefono VARCHAR(20) NULL,
    id_rol INT NOT NULL REFERENCES ROLES(id_rol) ON DELETE RESTRICT,
    laboratorio_asignado_id INT NULL REFERENCES AULAS(id_aula) ON DELETE SET NULL,
    is_leader BOOLEAN NOT NULL DEFAULT FALSE,
    debe_cambiar_password BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_registro TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. EQUIPOS E INVENTARIO
CREATE TABLE IF NOT EXISTS EQUIPOS (
    id_equipo INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo VARCHAR(50) NOT NULL,
    identificador VARCHAR(50) NOT NULL UNIQUE,
    id_aula INT NOT NULL REFERENCES AULAS(id_aula) ON DELETE RESTRICT,
    estado_actual VARCHAR(30) NOT NULL DEFAULT 'Operativo'
        CHECK (estado_actual IN ('Operativo', 'En Mantenimiento', 'Inoperativo'))
);

-- 5. TICKETS DE SOPORTE
-- id_aula es NOT NULL (requerimiento estricto para enrutamiento automático).
-- id_equipo es NULLABLE (permite reportar fallas generales del aula/red/proyector).
CREATE TABLE IF NOT EXISTS TICKETS (
    id_ticket INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_ticket VARCHAR(100) NOT NULL,
    descripcion TEXT NOT NULL,
    fecha_registro TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    estado VARCHAR(30) NOT NULL DEFAULT 'Abierto'
        CHECK (estado IN ('Abierto', 'En Proceso', 'Resuelto', 'Cerrado')),
    id_usuario UUID NOT NULL REFERENCES USUARIOS(id_usuario) ON DELETE RESTRICT,
    id_tecnico UUID NULL REFERENCES USUARIOS(id_usuario) ON DELETE SET NULL,
    id_aula INT NOT NULL REFERENCES AULAS(id_aula) ON DELETE RESTRICT,
    id_equipo INT NULL REFERENCES EQUIPOS(id_equipo) ON DELETE SET NULL
);

-- Relación N:M entre Tickets y Tipos de Problema
CREATE TABLE IF NOT EXISTS TICKETS_PROBLEMAS (
    id_ticket INT NOT NULL REFERENCES TICKETS(id_ticket) ON DELETE CASCADE,
    id_tipo_problema INT NOT NULL REFERENCES TIPOS_PROBLEMA(id_tipo_problema) ON DELETE RESTRICT,
    PRIMARY KEY (id_ticket, id_tipo_problema)
);

-- 6. HISTORIAL, NOTIFICACIONES Y SOLUCIONES

-- Auditoría de Cambios de Estado
CREATE TABLE IF NOT EXISTS HISTORIAL_ESTADO (
    id_historial INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_ticket INT NOT NULL REFERENCES TICKETS(id_ticket) ON DELETE CASCADE,
    estado_anterior VARCHAR(30) NOT NULL,
    estado_actual VARCHAR(30) NOT NULL,
    fecha_cambio TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    id_usuario UUID NOT NULL REFERENCES USUARIOS(id_usuario) ON DELETE RESTRICT
);

-- Bandeja de Notificaciones Internas (In-App)
CREATE TABLE IF NOT EXISTS NOTIFICACIONES (
    id_notificacion INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_ticket INT NOT NULL REFERENCES TICKETS(id_ticket) ON DELETE CASCADE,
    id_usuario UUID NOT NULL REFERENCES USUARIOS(id_usuario) ON DELETE CASCADE,
    mensaje VARCHAR(255) NOT NULL,
    fecha TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    leido BOOLEAN NOT NULL DEFAULT FALSE
);

-- Bitácora de Soluciones Técnicas
CREATE TABLE IF NOT EXISTS SOLUCIONES (
    id_solucion INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_ticket INT NOT NULL REFERENCES TICKETS(id_ticket) ON DELETE CASCADE,
    id_usuario UUID NOT NULL REFERENCES USUARIOS(id_usuario) ON DELETE RESTRICT,
    texto TEXT NOT NULL,
    fecha TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==============================================================================
-- 7. ÍNDICES DE RENDIMIENTO (Optimización para Consultas y Filtros)
-- ==============================================================================
CREATE INDEX IF NOT EXISTS idx_tickets_id_aula ON TICKETS(id_aula);
CREATE INDEX IF NOT EXISTS idx_tickets_id_equipo ON TICKETS(id_equipo);
CREATE INDEX IF NOT EXISTS idx_tickets_id_tecnico ON TICKETS(id_tecnico);
CREATE INDEX IF NOT EXISTS idx_tickets_id_usuario ON TICKETS(id_usuario);
CREATE INDEX IF NOT EXISTS idx_tickets_estado ON TICKETS(estado);

CREATE INDEX IF NOT EXISTS idx_usuarios_lab ON USUARIOS(laboratorio_asignado_id);
CREATE INDEX IF NOT EXISTS idx_usuarios_rol ON USUARIOS(id_rol);
CREATE INDEX IF NOT EXISTS idx_equipos_aula ON EQUIPOS(id_aula);

CREATE INDEX IF NOT EXISTS idx_historial_ticket ON HISTORIAL_ESTADO(id_ticket);
CREATE INDEX IF NOT EXISTS idx_notificaciones_usuario ON NOTIFICACIONES(id_usuario);
CREATE INDEX IF NOT EXISTS idx_soluciones_ticket ON SOLUCIONES(id_ticket);

-- ==============================================================================
-- 8. SEGURIDAD (Row Level Security - RLS)
-- Se activa RLS para proteger la base de datos de accesos front-end no autorizados.
-- El backend de FastAPI opera con rol con privilegios elevados (service_role / postgres).
-- ==============================================================================
ALTER TABLE ROLES ENABLE ROW LEVEL SECURITY;
ALTER TABLE AULAS ENABLE ROW LEVEL SECURITY;
ALTER TABLE TIPOS_PROBLEMA ENABLE ROW LEVEL SECURITY;
ALTER TABLE USUARIOS ENABLE ROW LEVEL SECURITY;
ALTER TABLE EQUIPOS ENABLE ROW LEVEL SECURITY;
ALTER TABLE TICKETS ENABLE ROW LEVEL SECURITY;
ALTER TABLE TICKETS_PROBLEMAS ENABLE ROW LEVEL SECURITY;
ALTER TABLE HISTORIAL_ESTADO ENABLE ROW LEVEL SECURITY;
ALTER TABLE NOTIFICACIONES ENABLE ROW LEVEL SECURITY;
ALTER TABLE SOLUCIONES ENABLE ROW LEVEL SECURITY;

-- ==============================================================================
-- 9. DATOS INICIALES (Catálogos Semilla)
-- ==============================================================================
INSERT INTO ROLES (nombre) 
VALUES 
    ('Administrador'),
    ('Técnico'),
    ('Maestro')
ON CONFLICT (nombre) DO NOTHING;

INSERT INTO TIPOS_PROBLEMA (nombre)
VALUES 
    ('Falla de Hardware'),
    ('Falla de Software'),
    ('Problema de Red / Internet'),
    ('Proyector / Audio')
ON CONFLICT (nombre) DO NOTHING;
